Add Apollo Block III+ Service Module & Apollo Block IV Engine
KSP-RO/ROCapsules pull request #66
Opened 2020-11-07 19:16 UTC by vader111

Add Apollo Block III+ Service Module & Apollo Block IV Engine Plus fixes for other issues.

2020-11-07 19:31 UTC, vader111 commented
Will Also Need https://github.com/Standecco/ROKerbalism/pull/80

2020-11-10 15:31 UTC, vader111 commented
(Ready To Review)

2020-11-22 16:05 UTC, DRVeyl requested changes

2020-11-22 16:05 UTC, DRVeyl commented on GameData/ROCapsules/PartConfigs/Apollo ETS/ApolloEngineBlockV.cfg
> +	RP0conf = true
Do not set RP0conf

2020-11-22 16:05 UTC, DRVeyl commented on GameData/ROCapsules/PartConfigs/Apollo ETS/ApolloEngineBlockV.cfg
> +		gimbalResponseSpeed = True
True is probably not going to work for a speed

2020-11-22 16:05 UTC, DRVeyl commented on GameData/ROCapsules/PartConfigs/Apollo ETS/ApolloHGABlockIII.cfg
> +}
The ModuleRealAntenna modules were intentionally duplicated to provide both an omni and a steerable dish.  Is that not correct?

2020-11-22 16:05 UTC, DRVeyl commented on GameData/ROCapsules/PartConfigs/Apollo ETS/ApolloHGABlockV.cfg
> -		RFBand = S
The ModuleRealAntenna modules were intentionally duplicated to provide both an omni and a steerable dish. Is that not correct?

2020-11-22 16:39 UTC, DRVeyl approved these changes

2020-11-23 15:17 UTC, DRVeyl commented
I'd appreciate anyone doing some functional testing of these changes before I actually merge.  I'm mostly doing a code review.

2021-01-13 03:38 UTC, merged