Update LEMAscent.cfg for 1.10.1
KSP-RO/ROCapsules pull request #78
Opened 2021-01-26 13:03 UTC by Jeceratops

Patch is orignally made by felixu (I believe) and makes the LEM work on 1.10.1 as intented. Doesn't frezee on loading. Only affects the LEMs config

Thanks Standecco!

2021-02-19 17:28 UTC, DRVeyl requested changes
Can you fix some of the issues, and possibly remove a lot of the "changes" that actually make all the whitespace/indentation actively worse?

2021-02-19 17:28 UTC, DRVeyl commented on GameData/ROCapsules/PartConfigs/LEM/LEMAscent.cfg
> +
Do not set RP0conf here.  That is RP0's job.

2021-02-19 17:28 UTC, DRVeyl commented on GameData/ROCapsules/PartConfigs/LEM/LEMAscent.cfg
Why all the messing with whitespace, to make things -not- consistent?

2021-02-19 17:28 UTC, DRVeyl commented on GameData/ROCapsules/PartConfigs/LEM/LEMAscent.cfg
> +
Why all the re-ordering?  Makes it look like a lot more changes that someone needs to review and see that, in fact, nothing changed.

2021-02-19 17:28 UTC, DRVeyl commented on GameData/ROCapsules/PartConfigs/LEM/LEMAscent.cfg
> +        hasHibernation = True
Stop breaking the indenting ;)

2021-02-19 17:28 UTC, DRVeyl commented on GameData/ROCapsules/PartConfigs/LEM/LEMAscent.cfg
> -@PART[ROC-LEMAscent]:NEEDS[RasterPropMonitor]
Why did you break this patch structure, and not include NEEDS[RasterPropMonitor] when you declared its fields above instead?

2021-02-22 10:06 UTC, Shaggygoblin commented
so... this does work to fix the 1.10.x load freeze, arguable whitepace concerns aside?

2021-02-22 14:18 UTC, DRVeyl commented
Only laughable if you have no role in maintaining the codebase or in QC'ing changes across several projects.
Also was reported that this patch breaks animations.  So feedback on that would be appreciated.
You can view the file directly here by going to the FIles Changed page, then selecting View File in:
![image](https://user-images.githubusercontent.com/25906300/108720435-ccaf2180-74ee-11eb-90ea-f642faec8bf5.png)

and pasting the result into your own copy of the original.  You can also visit Jceratops' fork and get the file directly, rather than cloning/forking his repo.

2021-02-22 18:24 UTC, Shaggygoblin commented
This does, indeed, fix the NRE Freeze while loading LEM for me. Usability confirmed, if not readability.

aside: While I do understand and share your view on readability, I find it trivial in weight against functionality.  When peer'ing, I look past the readability flaws and get to the meat of it: does it work or not?  If it works, we clean it up.  If not, fix it. Rinse, repeat.

2021-02-23 02:15 UTC, vader111 commented
Just me looking at how the code has been changed is making me need to bleach my eyes out, your basically undoing all the formatting changes i made to tidy it up and standardize it.

2021-02-23 02:17 UTC, vader111 commented
@Shaggygoblin all you needed to do was add useMultipleDragCubes = false to all the ModuleAnimateGeneric modules.

2021-02-23 02:18 UTC, vader111 commented
@Shaggygoblin Might be easier for you to close this PR and let me create a PR.

2021-02-23 16:08 UTC, closed without merging

2021-02-23 21:01 UTC, Shaggygoblin commented
I didn't modify anything.  My musings were on the content as it was.  I merely added this file to the install, and it worked to finish loading.  I was asked to feedback on animations and I did.  I made no modifications to the code.